### ISSUE TITLE
Error en la validación 

### ISSUE THREAD

**Issue by edisonperez** [edisonperez/gwybio#20]
Cuando se realiza una invocación de validación de un DNI determinado, se tiene el siguiente error: 

```
[5/20/15 10:03:54:620 PET] 000004c9 SystemErr     R May 20, 2015 10:03:54 AM null null
AUDIT: chain.started
[5/20/15 10:03:54:650 PET] 000004c9 SystemErr     R INFO: Found persistence provider "org.eclipse.persistence.jpa.PersistenceProvider". OpenJPA will not be used.
[5/20/15 10:03:54:660 PET] 000004c9 SystemErr     R INFO: Found persistence provider "org.eclipse.persistence.jpa.PersistenceProvider". OpenJPA will not be used.
[5/20/15 10:03:54:676 PET] 000004c9 SystemErr     R Local Exception Stack: 
Exception [EclipseLink-7144] (Eclipse Persistence Services - 2.0.0.v20091127-r5931): org.eclipse.persistence.exceptions.ValidationException
Exception Description: SEQ_GEN_IDENTITY: platform DatabasePlatform does not support NativeSequence.
	at org.eclipse.persistence.exceptions.ValidationException.platformDoesNotSupportSequence(ValidationException.java:1988)
	at org.eclipse.persistence.sequencing.NativeSequence.onConnect(NativeSequence.java:143)
	at org.eclipse.persistence.sequencing.Sequence.onConnect(Sequence.java:264)
	at org.eclipse.persistence.internal.sequencing.SequencingManager.onConnectAllSequences(SequencingManager.java:843)
	at org.eclipse.persistence.internal.sequencing.SequencingManager.onConnect(SequencingManager.java:706)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.initializeSequencing(DatabaseSessionImpl.java:148)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.initializeDescriptors(DatabaseSessionImpl.java:420)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.initializeDescriptors(DatabaseSessionImpl.java:406)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.postConnectDatasource(DatabaseSessionImpl.java:671)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.login(DatabaseSessionImpl.java:633)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:214)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:195)
	at com.zy.bio.gw.web.rpc.db.IbtmMovimientoJpaController.getEntityManager(IbtmMovimientoJpaController.java:28)
	at com.zy.bio.gw.web.rpc.db.IbtmMovimientoJpaController.create(IbtmMovimientoJpaController.java:34)
	at com.zy.bio.gw.web.rpc.db.HandleData.logPadre(HandleData.java:147)
	at com.zy.bio.gw.web.rpc.ws.BioGatewayRPCWSImpl.regTxnParent(BioGatewayRPCWSImpl.java:2018)
	at com.zy.bio.gw.web.rpc.ws.BioGatewayRPCWSImpl.verifyClient(BioGatewayRPCWSImpl.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
	at java.lang.reflect.Method.invoke(Method.java:611)
	at com.ibm.ws.webservices.engine.dispatchers.java.JavaDispatcher.invokeMethod(JavaDispatcher.java:203)
	at com.ibm.ws.webservices.engine.dispatchers.java.JavaDispatcher.invokeOperation(JavaDispatcher.java:158)
	at com.ibm.ws.webservices.engine.dispatchers.SoapRPCProcessor.processRequestResponse(SoapRPCProcessor.java:490)
	at com.ibm.ws.webservices.engine.dispatchers.SoapRPCProcessor.processMessage(SoapRPCProcessor.java:433)
	at com.ibm.ws.webservices.engine.dispatchers.BasicDispatcher.processMessage(BasicDispatcher.java:134)
	at com.ibm.ws.webservices.engine.dispatchers.java.SessionDispatcher.invoke(SessionDispatcher.java:204)
	at com.ibm.ws.webservices.engine.PivotHandlerWrapper.invoke(PivotHandlerWrapper.java:264)
	at com.ibm.ws.webservices.engine.handlers.jaxrpc.JAXRPCHandler.invoke(JAXRPCHandler.java:153)
	at com.ibm.ws.webservices.engine.handlers.WrappedHandler.invoke(WrappedHandler.java:64)
	at com.ibm.ws.webservices.engine.PivotHandlerWrapper.invoke(PivotHandlerWrapper.java:264)
	at com.ibm.ws.webservices.engine.PivotHandlerWrapper.invoke(PivotHandlerWrapper.java:264)
	at com.ibm.ws.webservices.engine.WebServicesEngine.invoke(WebServicesEngine.java:336)
	at com.ibm.ws.webservices.engine.transport.http.WebServicesServlet.doPost(WebServicesServlet.java:1153)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:595)
	at com.ibm.ws.webservices.engine.transport.http.WebServicesServletBase.service(WebServicesServletBase.java:344)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1225)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:775)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:457)
	at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:178)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1032)
	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:87)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:908)
	at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1662)
	at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:195)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:459)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:526)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:312)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.ready(HttpInboundLink.java:283)
	at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:214)
	at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:113)
	at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:165)
	at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
	at com.ibm.io.async.AsyncChannelFuture$1.run(AsyncChannelFuture.java:205)
	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1815)
[5/20/15 10:03:54:677 PET] 000004c9 SystemErr     R Local Exception Stack: 
Exception [EclipseLink-7144] (Eclipse Persistence Services - 2.0.0.v20091127-r5931): org.eclipse.persistence.exceptions.ValidationException
Exception Description: SEQ_GEN_IDENTITY: platform DatabasePlatform does not support NativeSequence.
	at org.eclipse.persistence.exceptions.ValidationException.platformDoesNotSupportSequence(ValidationException.java:1988)
	at org.eclipse.persistence.sequencing.NativeSequence.onConnect(NativeSequence.java:143)
	at org.eclipse.persistence.sequencing.Sequence.onConnect(Sequence.java:264)
	at org.eclipse.persistence.internal.sequencing.SequencingManager.onConnectAllSequences(SequencingManager.java:843)
	at org.eclipse.persistence.internal.sequencing.SequencingManager.onConnect(SequencingManager.java:706)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.initializeSequencing(DatabaseSessionImpl.java:148)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.initializeDescriptors(DatabaseSessionImpl.java:420)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.initializeDescriptors(DatabaseSessionImpl.java:406)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.postConnectDatasource(DatabaseSessionImpl.java:671)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.login(DatabaseSessionImpl.java:633)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:214)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:195)
	at com.zy.bio.gw.web.rpc.db.IbtmMovimientoJpaController.getEntityManager(IbtmMovimientoJpaController.java:28)
	at com.zy.bio.gw.web.rpc.db.IbtmMovimientoJpaController.findIbtmMovimiento(IbtmMovimientoJpaController.java:100)
	at com.zy.bio.gw.web.rpc.db.IbtmMovimientoJpaController.create(IbtmMovimientoJpaController.java:41)
	at com.zy.bio.gw.web.rpc.db.HandleData.logPadre(HandleData.java:147)
	at com.zy.bio.gw.web.rpc.ws.BioGatewayRPCWSImpl.regTxnParent(BioGatewayRPCWSImpl.java:2018)
	at com.zy.bio.gw.web.rpc.ws.BioGatewayRPCWSImpl.verifyClient(BioGatewayRPCWSImpl.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
	at java.lang.reflect.Method.invoke(Method.java:611)
	at com.ibm.ws.webservices.engine.dispatchers.java.JavaDispatcher.invokeMethod(JavaDispatcher.java:203)
	at com.ibm.ws.webservices.engine.dispatchers.java.JavaDispatcher.invokeOperation(JavaDispatcher.java:158)
	at com.ibm.ws.webservices.engine.dispatchers.SoapRPCProcessor.processRequestResponse(SoapRPCProcessor.java:490)
	at com.ibm.ws.webservices.engine.dispatchers.SoapRPCProcessor.processMessage(SoapRPCProcessor.java:433)
	at com.ibm.ws.webservices.engine.dispatchers.BasicDispatcher.processMessage(BasicDispatcher.java:134)
	at com.ibm.ws.webservices.engine.dispatchers.java.SessionDispatcher.invoke(SessionDispatcher.java:204)
	at com.ibm.ws.webservices.engine.PivotHandlerWrapper.invoke(PivotHandlerWrapper.java:264)
	at com.ibm.ws.webservices.engine.handlers.jaxrpc.JAXRPCHandler.invoke(JAXRPCHandler.java:153)
	at com.ibm.ws.webservices.engine.handlers.WrappedHandler.invoke(WrappedHandler.java:64)
	at com.ibm.ws.webservices.engine.PivotHandlerWrapper.invoke(PivotHandlerWrapper.java:264)
	at com.ibm.ws.webservices.engine.PivotHandlerWrapper.invoke(PivotHandlerWrapper.java:264)
	at com.ibm.ws.webservices.engine.WebServicesEngine.invoke(WebServicesEngine.java:336)
	at com.ibm.ws.webservices.engine.transport.http.WebServicesServlet.doPost(WebServicesServlet.java:1153)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:595)
	at com.ibm.ws.webservices.engine.transport.http.WebServicesServletBase.service(WebServicesServletBase.java:344)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1225)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:775)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:457)
	at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:178)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1032)
	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:87)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:908)
	at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1662)
	at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:195)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:459)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:526)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:312)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.ready(HttpInboundLink.java:283)
	at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:214)
	at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:113)
	at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:165)
	at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
	at com.ibm.io.async.AsyncChannelFuture$1.run(AsyncChannelFuture.java:205)
	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1815)
```

**Comment by johnsevillano** [comment]
Por favor, indicar la cadena de parámetros de entrada que se envían desde el nacar al Gateway.

**Comment by edisonperez** [comment]
```
echo 'echo VALIDAR_NACIONAL L 08184928 1 36 41460156 118.216.51.96 P113039 IW9H 0 NONE 1 NONE 0241 1 NONE | exec /opt/java/bin/java -jar /opt/nacar/biometrico/ClienteWSRPCEclipse.jar > /opt/nacar/tmp/36/lector-biometrico-output.txt'
```

**Comment by edisonperez** [comment]
Datos adicionales: 

El DNI no se encontraba en la tabla de clientes. 
El error 8003 se daba para todos los casos. 
Reiniciando la aplicación se solucionó el tema. 

¿Cuál es el motivo del error? En producción es complicado reiniciar aplicaciones.

**Comment by johnsevillano** [comment]
Al analizar los logs vemos que al parecer no se desplegado el ultimo ear enviado o este no se ha desplegado correctamente o no se han sincronizado los nodos, ya que la traza en el log indica
BioGatewayRPCWS V2015 - v2 - compiled 08052015 cuando debería indicar 
BioGatewayRPCWS V2015 - v2 - compiled 13052015 (que corresponde al ultimo ear liberado) 
En caso de que se haya realizado al parecer los nodos no están sincronizado con el mismo ear desplegado, esto podría haber provocado ese problema de registro.
Recomendamos que después de hacer el deploy del ear en el clúster se sincronicen los cambios para ambos nodos was, para que se tenga la misma aplicación actualizada en ambos nodos.
El enlace con la aplicacion fue enviado el día 13 del presente , se indica a continuación el link.
http://dev.zytrust.com/submit/bbva/2da/extranjeros/server/ear/BioGatewayRPCWSEAR1_BBVA_FINAL_EXT.ear

**Comment by edisonperez** [comment]
Se ha descargado la última versión pero aún sigue saliendo lo siguiente en el log:

```
2015-05-20 15:14:22,760 : 0     : INFO  : WebContainer : 8 : com.zy.bio.gw.web.rpc.ws.BioGatewayRPCWSImpl(70) : BioGatewayRPCWS V2015 - v2 - compiled 08052015
````

**Comment by johnsevillano** [comment]
Se ha actualizado el ear con la traza indicada. Por favor realizar la descarga y el deploy correspondiente.
